language: node_js
node_js:
  - 8
cache:
  directories:
    - ~/.npm
notifications:
  email:
    recipients:
      - jae.b.bradley@gmail.com
    on_failure: always
script:
  - npm run lint
  - npm run test
after_success:
  - npm run codecov
